Tnw-clone  homepage
chrystalme/tnw-responsive-project pull request #2
Opened 2020-12-02 16:26 UTC by chrystalme

Please, take a look at my project so far.

2020-12-02 16:56 UTC, tirthajyoti-ghosh requested changes
# ⚠️ Invalid

The PR description and the README is not professional. Please always make sure that your README is complete and add a description of the project in your PR description.

I am marking this project invalid as it's considered an unprofessional project submission. Please request a review when you have made it professional.

2020-12-02 20:55 UTC, jubaan requested changes
# :rotating_light: :rotating_light: :rotating_light: :construction: Status: Invalid :construction: :rotating_light: :rotating_light: :rotating_light:

The project is marked as invalid for the next reasons.

- [ ] PR should be descriptive.

- [ ] Project should have a professional README.

- [ ] Project should be a working finished version.

- [ ] All linter checks should Pass.

DON'T submit your project until the project is finished. If you need to review something or need an opinion from a TSE, please contact them through slack.

# :rotating_light: :rotating_light: :rotating_light: :construction: Invalid Invalid :construction: :rotating_light: :rotating_light: :rotating_light:

2020-12-03 12:21 UTC, chrystalme commented
> # 🚨 🚨 🚨 🚧 Status: Invalid 🚧 🚨 🚨 🚨
> The project is marked as invalid for the next reasons.
> 
> * [ ]  PR should be descriptive.
> * [ ]  Project should have a professional README.
> * [ ]  Project should be a working finished version.
> * [ ]  All linter checks should Pass.
> 
> DON'T submit your project until the project is finished. If you need to review something or need an opinion from a TSE, please contact them through slack.
> 
> # 🚨 🚨 🚨 🚧 Invalid Invalid 🚧 🚨 🚨 🚨

2020-12-03 12:21 UTC, chrystalme commented
Hello TSE, I don't know what you mean. My project is descriptive and the read me is from the template

2020-12-04 18:03 UTC, mahmoud717 requested changes
### Changes required ♻️ 

**Hello @chrystalme  & @tumwinep**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

### General

- [ ] the pr should have a descriptive description. 

- [ ] please take into consideration the cloned page will not be approved unless it looks exactly like the original one. that means that it should have the same item positioning, dimensions, responsiveness, appearance, and margins.

- [ ] also, your project should follow the mobile-first approach. meaning that it should flawless in mobile view.

- [ ] the tablet view looks weird
![asafsfas](https://user-images.githubusercontent.com/60571499/101197038-3f380000-366a-11eb-9527-be915fa4e5a6.PNG)

### navbar 

- [ ] the navbar disappears at the mobile view 

### showcase section

- Large version

- [ ] It contains one bigger image on the leftmost part of the row (around two thirds of the width)

- [ ] It contains two smaller images on the rightmost part of the row (one above another) (link to page)

- [ ] It contains TWN logo at the top left corner of the row (link to page)

- medium version 

- [ ] TWN logo disappears

- small version

- [ ] All images take the maximum width and are aligned in one column


###  latest news section


- large version

- [ ] it should contain 4 articles per row




### latest deals section

- [ ] the margins around and between the articles should look exactly like the original one.


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

2020-12-04 18:03 UTC, mahmoud717 commented on index.html
> +                        </div> -->
- the code should not include any commented code. please fix this

2020-12-04 18:03 UTC, mahmoud717 commented on index.html
> +                            </a> -->
- the code should not include any commented code. please fix this

2020-12-04 18:03 UTC, mahmoud717 commented on index.html
> +        </nav> -->
- the code should not include any commented code. please fix this

2020-12-18 12:06 UTC, merged